import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./background.css";


const geistSans = localFont({
  src: "./fonts/geist/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/geist/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});



// <>
//   <meta charSet="UTF-8" />
//   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//   <link
//     rel="icon"
//     href="/imgs/icon200x200.png"
//     type="image/icon type"
//   />
//   <title>Pinefolio</title>
//   <header></header>

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
